[package]
name = "genes-just-want-to-have-fun"
version = "0.1.0"
authors = ["Ofer Affias <ofer@3dsig.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
